### ISSUE TITLE
Nerdbox duplicates content within its shim element

### ISSUE THREAD

**Issue by jtrim** [mikepack/nerdbox#13]
If I recall correctly, this was intentional but I don't remember why. Do happen to remember why this is the case?

**Comment by jtrim** [comment]
Sorry, just read through #11. Closing this.

**Comment by mikepack** [comment]
Unfortunately, this still lives. @ajaswa what was the solution we had before the shim?

**Comment by ajaswa** [comment]
Basically if you don't have the shim the content can't be more than the height/width of the modal/lightbox, otherwise the content gets cut off. The height and width are based on the current browser window. The "offending" CSS: https://github.com/mikepack/nerdbox/blob/master/src/nerdbox.css#L42-L43
