### ISSUE TITLE
Calling `Nerdbox.close()` when there is no Nerdbox open causes a Javascript error.

### ISSUE THREAD

**Issue by jtrim** [mikepack/nerdbox#2]
One could argue that we should only be closing a nerdbox when we know we've opened one, but I just ran into an edgecase that led me back to this problem, so it may be worth fixing.

**Comment by mikepack** [comment]
Is there an error you're seeing? Does [this spec](https://github.com/mikepack/nerdbox/blob/master/spec/nerdbox/nerdbox_spec.js#L305-L307) not cover this case?

**Comment by jtrim** [comment]
I can point you to the line in a jiffy. Just a sec...

**Comment by jtrim** [comment]
See [here](https://github.com/mikepack/nerdbox/blob/df6dd6876185af43afa074314b876ac82ccef676/src/nerdbox.js#L51). The error I was getting is something like:

```
no method `options` for undefined
```

**Comment by jtrim** [comment]
Regarding your test case, there must be something else going on. That case should cover it, but is it possible the state of `Nerdbox._currentlyOpen` is dirtied by a previously-executed test?

**Comment by mikepack** [comment]
You're correct. If I run that spec in isolation, it fails. I'll get this fixed.

**Comment by mikepack** [comment]
Fixed in ac3602e3bb4d3ef07b05f51a2f4609a7eea6b9c4
