### ISSUE TITLE
Automatic page refresh when using ajax with grunt

### ISSUE THREAD

**Issue by mbuehrig** [mikepack/nerdbox#21]
If you set an .html link as href, after the successfull ajax request it automatics reloads the page. This is due, to the fix set DataType for Ajax, when we removed that line it works.

Possible Solution: Possibility to set the dataType via option param.

**Comment by mikepack** [comment]
What type of data are you returning other than HTML? What line did you remove to get this to work?

I'm not having any problems opening .html links, see the [demo file](https://github.com/mikepack/nerdbox/blob/master/demo.html#L18).

**Comment by mbuehrig** [comment]
The Problem appears when using grunt to automatic refresh the page and working with swig (twig) templates. 

We didn't remove any lines, we modified it local so, it's possible to set dataType via options of nerdbox.

Regards,
Marcel
