### ISSUE TITLE
Vertical overflow not scrolling

### ISSUE THREAD

**Issue by mikepack** [mikepack/nerdbox#4]
When content (eg an image) is larger than the maximum size of the lightbox, the lightbox does not vertically scroll. It horizontally scrolls properly.

**Comment by ajaswa** [comment]
Took a stab at this today:

It seems that the overflow: auto on .nb-content needs a parent with an explicit height. https://github.com/mikepack/nerdbox/blob/master/src/nerdbox.css#L80

Tried many things to arrive at this, any thoughts or suggestions are welcome.

**Comment by mikepack** [comment]
Fixed in b956ee3ecdf0677ebd4efbad1300945f4c7f3cf9
